# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Hub login
        run: docker login --username ${{ secrets.USERNAME_HUB }} --password ${{ secrets.PASSWORD_HUB }}
      - name: Use Node.js 16.x
        env:
          process.env.CI: false
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - name: Build Docker
        run: docker build --tag ${{ secrets.USERNAME_HUB }}/cinema-ui:latest .
      - name: Push into DockerHub
        run: docker push ${{ secrets.USERNAME_HUB }}/cinema-ui:latest